/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Image;
import javax.swing.ImageIcon;
import Business.Person;
import javax.swing.JLabel;

/**
 *
 * @author shivibhatt
 */

public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     * @param  person
     */
    
    public ViewJPanel(Person person) {
        initComponents();
         displayPerson(person);
    }
    private void displayPerson(Person person){
        
        JLabel label = new JLabel(ResizeImage(person.getAddpic()));
        viewPicture.add(label);
        System.out.println(" Shivi Clicks");
        
    }
     
    public ImageIcon ResizeImage(String addPic)
    {
        
        System.out.print(" Shivi Clicks");
        ImageIcon MyImage = new ImageIcon(addPic);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(680, 462, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewPicture = new javax.swing.JPanel();

        jLabel1.setText("VIEW PICTURE");

        viewPicture.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(viewPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(viewPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(429, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel viewPicture;
    // End of variables declaration//GEN-END:variables
}
