/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSigns;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shivibhatt
 */
public class abnormalVitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form abnormalVitalJPanel
     */
    //abnormalVitalJPanel abnormalPanel;
    private VitalSignHistory vsh;
    private double max;
    private double min;
    private ArrayList<VitalSigns> abnormalList;

    public abnormalVitalJPanel(VitalSignHistory vsh, double max, double min) {
        initComponents();
        this.vsh = vsh;
        this.max=max;
        this.min=min;
        populateTable();
        //display(vsh);

        tempTextField_abnormal.setEnabled(false);
        bloodTextField_abnormal.setEnabled(false);
        pulseTextField_abnormal.setEnabled(false);
        dateTextField_abnormal.setEnabled(false);

    }
    
//    
//    private void display(VitalSignHistory vsh){
//    VitalSigns vs = new VitalSigns();
//    System.out.println("Shivi clicked");
//    
//    
//
//    
//   abnormalList= vsh.getAbnormalList(max, min);
//        
//        
//    }

    /* Create and Display the Dialog*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        vitalSignsTable_abnormal = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        detailButton_abnormal = new javax.swing.JButton();
        deleteButton_abnormal = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        bloodTextField_abnormal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dateTextField_abnormal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tempTextField_abnormal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pulseTextField_abnormal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        vitalSignsTable_abnormal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ));
        jScrollPane3.setViewportView(vitalSignsTable_abnormal);

        jLabel7.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Abnormal Vital Sign");

        detailButton_abnormal.setText("Details");
        detailButton_abnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailButton_abnormalActionPerformed(evt);
            }
        });

        deleteButton_abnormal.setText("Delete");
        deleteButton_abnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton_abnormalActionPerformed(evt);
            }
        });

        bloodTextField_abnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTextField_abnormalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("Pulse:");

        dateTextField_abnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextField_abnormalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Bloodpressure:");

        tempTextField_abnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempTextField_abnormalActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Date: ");

        pulseTextField_abnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulseTextField_abnormalActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setText("Temperature: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pulseTextField_abnormal, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tempTextField_abnormal, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodTextField_abnormal, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(139, 139, 139)
                        .addComponent(dateTextField_abnormal, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detailButton_abnormal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton_abnormal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(detailButton_abnormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton_abnormal)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempTextField_abnormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodTextField_abnormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulseTextField_abnormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTextField_abnormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void detailButton_abnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailButton_abnormalActionPerformed
        // TODO add your handling code here:
        int selectedRow = vitalSignsTable_abnormal.getSelectedRow();

        if (selectedRow >= 0) {
            VitalSigns vs = (VitalSigns) vitalSignsTable_abnormal.getValueAt(selectedRow, 0);
            
            tempTextField_abnormal.setText(vs.getTemperature() + "");
            bloodTextField_abnormal.setText(vs.getBloodPressure() + "");
            pulseTextField_abnormal.setText(vs.getPulse() + "");
            dateTextField_abnormal.setText(vs.getDate());
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_detailButton_abnormalActionPerformed

    private void deleteButton_abnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton_abnormalActionPerformed
        // TODO add your handling code here:
        int selectedRow = vitalSignsTable_abnormal.getSelectedRow();

        if (selectedRow >= 0) {
            VitalSigns vs = (VitalSigns) vitalSignsTable_abnormal.getValueAt(selectedRow, 0);
            vsh.deleteVital(vs);
            JOptionPane.showMessageDialog(null, "Vital Sign deleted.");
            populateTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
        tempTextField_abnormal.setText("");
        bloodTextField_abnormal.setText("");
        pulseTextField_abnormal.setText("");
        dateTextField_abnormal.setText("");
    }//GEN-LAST:event_deleteButton_abnormalActionPerformed

    private void dateTextField_abnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextField_abnormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextField_abnormalActionPerformed

    private void pulseTextField_abnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulseTextField_abnormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pulseTextField_abnormalActionPerformed

    private void bloodTextField_abnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTextField_abnormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTextField_abnormalActionPerformed

    private void tempTextField_abnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempTextField_abnormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempTextField_abnormalActionPerformed

    private void setAllEnabled(boolean b) {

        tempTextField_abnormal.setEnabled(b);
        bloodTextField_abnormal.setEnabled(b);
        pulseTextField_abnormal.setEnabled(b);
        dateTextField_abnormal.setEnabled(b);

    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) vitalSignsTable_abnormal.getModel();
        dtm.setRowCount(0);
        abnormalList=vsh.getAbnormalList(max, min);
        for (VitalSigns vs :abnormalList) {
            Object row[] = new Object[2];
            row[0] = vs;
            row[1] = vs.getBloodPressure();
            dtm.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodTextField_abnormal;
    private javax.swing.JTextField dateTextField_abnormal;
    private javax.swing.JButton deleteButton_abnormal;
    private javax.swing.JButton detailButton;
    private javax.swing.JButton detailButton1;
    private javax.swing.JButton detailButton2;
    private javax.swing.JButton detailButton_abnormal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField pulseTextField_abnormal;
    private javax.swing.JTextField tempTextField_abnormal;
    private javax.swing.JTable vitalSignsTable;
    private javax.swing.JTable vitalSignsTable_abnormal;
    // End of variables declaration//GEN-END:variables
}
