/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author shivibhatt
 */
import Business.Person;
import Business.Address;
import Business.BankAccountInfo;
import Business.DemographicInfo;
import Business.DriverLicInfo;
import Business.MedicalRecordInfo;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;

//import javax.swing.JTextField;
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     *
     * @param person
     */
    private Person person;
    private DriverLicInfo driverLicInfo;
    private String imagePath;
    private String accountType1;
    private String accountType2;

    public CreateJPanel(Person person) {
        initComponents();
        this.person = person;
        this.driverLicInfo = new DriverLicInfo();
        //tfield = new JTextField();
        //tfield.setColumns(size);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        createSBankName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        createSRouting = new javax.swing.JTextField();
        createSBalance = new javax.swing.JTextField();
        createSAccount = new javax.swing.JTextField();
        createSType = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        createCBankName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        createCRouting = new javax.swing.JTextField();
        createCBalance = new javax.swing.JTextField();
        createCAccount = new javax.swing.JTextField();
        createCType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        createMedicalNumber = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        createAllergy2 = new javax.swing.JTextField();
        createAllergy1 = new javax.swing.JTextField();
        createAllergy3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        createWeight = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        createHeight = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        createFirstName = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        createLastName = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        createPhoneNumber = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        createDateOfBirth = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        createAge = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        createSSN = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        createStreetLine1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        createStreetLine2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        createCity = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        createState = new javax.swing.JTextField();
        createCountry = new javax.swing.JTextField();
        createZipCode = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        createDrLicNo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        createIssueDate = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        createExpiryDate = new javax.swing.JTextField();
        createBloodType = new javax.swing.JTextField();
        createAddPic = new javax.swing.JButton();
        fileNameLabel = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(233, 224, 219));
        setSize(new java.awt.Dimension(80, 26));

        jPanel7.setBackground(new java.awt.Color(233, 224, 219));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Bank Information"));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(233, 224, 219));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Bank Name");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel11.setText("Balance");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 56, -1, 20));

        jLabel12.setText("Routing#");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        createSBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSBankNameActionPerformed(evt);
            }
        });
        jPanel4.add(createSBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, 30));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText(" Type");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel26.setText("Account#");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        createSRouting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSRoutingActionPerformed(evt);
            }
        });
        jPanel4.add(createSRouting, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, 30));

        createSBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSBalanceActionPerformed(evt);
            }
        });
        jPanel4.add(createSBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 190, 30));

        createSAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSAccountActionPerformed(evt);
            }
        });
        jPanel4.add(createSAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 190, 30));

        createSType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account Type", "Saving", "Checking" }));
        createSType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSTypeActionPerformed(evt);
            }
        });
        jPanel4.add(createSType, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 190, 30));

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 1000, 120));

        jPanel5.setBackground(new java.awt.Color(233, 224, 219));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Bank Name");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel15.setText("Balance");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 56, -1, 20));

        jLabel16.setText("Routing#");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        createCBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCBankNameActionPerformed(evt);
            }
        });
        jPanel5.add(createCBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, 30));

        jLabel17.setText(" Type");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel37.setText("Account#");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        createCRouting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCRoutingActionPerformed(evt);
            }
        });
        jPanel5.add(createCRouting, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, 30));

        createCBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCBalanceActionPerformed(evt);
            }
        });
        jPanel5.add(createCBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 190, 30));

        createCAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCAccountActionPerformed(evt);
            }
        });
        jPanel5.add(createCAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 190, 30));

        createCType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account Type", "Saving", "Checking", " " }));
        createCType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCTypeActionPerformed(evt);
            }
        });
        jPanel5.add(createCType, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 190, 30));

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1000, 128));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("CREATE PERSON PROFILE");

        jPanel1.setBackground(new java.awt.Color(233, 224, 219));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Medical Record Information"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Medical Record#");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setText("Allergy 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel4.setText("Allergy 2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        createMedicalNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMedicalNumberActionPerformed(evt);
            }
        });
        jPanel1.add(createMedicalNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, 30));

        jLabel25.setText("Allergy 3");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        createAllergy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAllergy2ActionPerformed(evt);
            }
        });
        jPanel1.add(createAllergy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, 30));

        createAllergy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAllergy1ActionPerformed(evt);
            }
        });
        jPanel1.add(createAllergy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 190, 30));

        createAllergy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAllergy3ActionPerformed(evt);
            }
        });
        jPanel1.add(createAllergy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 190, 30));

        jPanel2.setBackground(new java.awt.Color(233, 224, 219));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Demographic Information"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setText("First Name");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        createWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createWeightActionPerformed(evt);
            }
        });
        jPanel2.add(createWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 190, 30));

        jLabel30.setText("Date Of Birth");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 56, -1, 20));

        createHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHeightActionPerformed(evt);
            }
        });
        jPanel2.add(createHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 190, 30));

        jLabel31.setText("Phone Number");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        createFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFirstNameActionPerformed(evt);
            }
        });
        jPanel2.add(createFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, 30));

        jLabel32.setText("Last Name");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        createLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLastNameActionPerformed(evt);
            }
        });
        jPanel2.add(createLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 190, 30));

        jLabel33.setText("Age");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 30, -1));

        createPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPhoneNumberActionPerformed(evt);
            }
        });
        jPanel2.add(createPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, 30));

        jLabel34.setText("SSN");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 86, 80, 20));

        createDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDateOfBirthActionPerformed(evt);
            }
        });
        jPanel2.add(createDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 190, 30));

        jLabel35.setText("Weight(Lbs)");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        createAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAgeActionPerformed(evt);
            }
        });
        jPanel2.add(createAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 190, 30));

        jLabel36.setText("Height(cm)");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, 30));

        createSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSSNActionPerformed(evt);
            }
        });
        jPanel2.add(createSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 190, 30));

        jPanel3.setBackground(new java.awt.Color(233, 224, 219));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Address Information"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Street Line 1");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel7.setText("State");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 56, -1, 20));

        jLabel8.setText("City");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        createStreetLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStreetLine1ActionPerformed(evt);
            }
        });
        jPanel3.add(createStreetLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, 30));

        jLabel9.setText("Street Line 2");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        createStreetLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStreetLine2ActionPerformed(evt);
            }
        });
        jPanel3.add(createStreetLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 190, 30));

        jLabel27.setText("Country");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        createCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCityActionPerformed(evt);
            }
        });
        jPanel3.add(createCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, 30));

        jLabel28.setText("Zip Code");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 86, 80, 20));

        createState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStateActionPerformed(evt);
            }
        });
        jPanel3.add(createState, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 190, 30));

        createCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCountryActionPerformed(evt);
            }
        });
        jPanel3.add(createCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 190, 30));

        createZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createZipCodeActionPerformed(evt);
            }
        });
        jPanel3.add(createZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 190, 30));

        jPanel6.setBackground(new java.awt.Color(233, 224, 219));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Driver's License Information"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("License Number");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel19.setText("Blood Type");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 56, -1, 20));

        jLabel20.setText("Expiry Date");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        createDrLicNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDrLicNoActionPerformed(evt);
            }
        });
        jPanel6.add(createDrLicNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, 30));

        jLabel21.setText("Issue Date");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        createIssueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createIssueDateActionPerformed(evt);
            }
        });
        jPanel6.add(createIssueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 190, 30));

        jLabel38.setText("Add Picture");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        createExpiryDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createExpiryDateActionPerformed(evt);
            }
        });
        jPanel6.add(createExpiryDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, 30));

        createBloodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBloodTypeActionPerformed(evt);
            }
        });
        jPanel6.add(createBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 190, 30));

        createAddPic.setIcon(new javax.swing.ImageIcon("/Users/shivibhatt/Documents/AED/GIT/Bhatt_Shivi_001027605/JavaApplication_Assignment1/Icons/icons8-add-image-16.png")); // NOI18N
        createAddPic.setText("Upload Picture");
        createAddPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAddPicActionPerformed(evt);
            }
        });
        jPanel6.add(createAddPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 40));
        jPanel6.add(fileNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 750, 20));

        createButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        createButton.setText("CREATE PROFILE");
        createButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE))
                        .addContainerGap(1054, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createButton)
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:

        //Demographic Details
        DemographicInfo demographic = new DemographicInfo();
        demographic.setFirstName(createFirstName.getText());
        demographic.setLastName(createLastName.getText());
        demographic.setDateOfBirth(createDateOfBirth.getText());
        demographic.setAge(createAge.getText());
        demographic.setPhoneNumber(createPhoneNumber.getText());
        demographic.setSSN(createSSN.getText());
        demographic.setWeight(createWeight.getText());
        demographic.setHeight(createHeight.getText());
        person.setDemographic(demographic);

        //Address Details
        Address address = new Address();
        address.setStreetLine1(createStreetLine1.getText());
        address.setStreetLine2(createStreetLine2.getText());
        address.setCity(createCity.getText());
        address.setState(createState.getText());
        address.setCountry(createCountry.getText());
        address.setZipcode(createZipCode.getText());
        person.setAddress(address);

        //Saving Bank Account
        BankAccountInfo savingBank = new BankAccountInfo();
        savingBank.setBankName(createSBankName.getText());
        savingBank.setType(accountType1);
        savingBank.setRouting(createSRouting.getText());
        savingBank.setAccountNumber(createSAccount.getText());
        savingBank.setBalance(createSBalance.getText());
        person.setSavingBank(savingBank);

        //Checking Bank Account
        BankAccountInfo checkingBank = new BankAccountInfo();
        checkingBank.setBankName(createSBankName.getText());
        checkingBank.setType(accountType2);
        checkingBank.setRouting(createSRouting.getText());
        checkingBank.setAccountNumber(createSAccount.getText());
        checkingBank.setBalance(createSBalance.getText());
        person.setCheckingBank(checkingBank);

        //Driver License Info
        DriverLicInfo driver = new DriverLicInfo();
        driver.setLicenseNumber(createDrLicNo.getText());
        driver.setIssueDate(createIssueDate.getText());
        driver.setExpiryDate(createExpiryDate.getText());
        driver.setImagePath(imagePath);
        driver.setBloodType(createBloodType.getText());
        person.setDriverLicense(driver);

        //Medical Record Info
        MedicalRecordInfo medical = new MedicalRecordInfo();
        medical.setMedicalRecordNumber(createMedicalNumber.getText());
        medical.setAllergy1(createAllergy1.getText());
        medical.setAllergy2(createAllergy2.getText());
        medical.setAllergy3(createAllergy3.getText());
        person.setMedical(medical);

        JOptionPane.showMessageDialog(null, "Person Profile Created Successfully");

    }//GEN-LAST:event_createButtonActionPerformed

    private void createFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createFirstNameActionPerformed

    private void createLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createLastNameActionPerformed

    private void createAddPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAddPicActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imagePath = selectedFile.getAbsolutePath();
            fileNameLabel.setText(imagePath);
        }

    }//GEN-LAST:event_createAddPicActionPerformed

    private void createPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPhoneNumberActionPerformed

    private void createDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createDateOfBirthActionPerformed

    private void createAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createAgeActionPerformed

    private void createSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createSSNActionPerformed

    private void createWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createWeightActionPerformed

    private void createHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createHeightActionPerformed

    private void createStreetLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStreetLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createStreetLine1ActionPerformed

    private void createStreetLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStreetLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createStreetLine2ActionPerformed

    private void createCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createCityActionPerformed

    private void createStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createStateActionPerformed

    private void createCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createCountryActionPerformed

    private void createZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createZipCodeActionPerformed

    private void createSBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createSBankNameActionPerformed

    private void createSRoutingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSRoutingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createSRoutingActionPerformed

    private void createSBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createSBalanceActionPerformed

    private void createSAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createSAccountActionPerformed

    private void createCBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createCBankNameActionPerformed

    private void createCRoutingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCRoutingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createCRoutingActionPerformed

    private void createCBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createCBalanceActionPerformed

    private void createCAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createCAccountActionPerformed

    private void createDrLicNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDrLicNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createDrLicNoActionPerformed

    private void createIssueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createIssueDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createIssueDateActionPerformed

    private void createExpiryDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createExpiryDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createExpiryDateActionPerformed

    private void createBloodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBloodTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createBloodTypeActionPerformed

    private void createMedicalNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMedicalNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createMedicalNumberActionPerformed

    private void createAllergy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAllergy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createAllergy1ActionPerformed

    private void createAllergy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAllergy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createAllergy2ActionPerformed

    private void createAllergy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAllergy3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createAllergy3ActionPerformed

    private void createSTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSTypeActionPerformed

        String sTypeStr = createSType.getSelectedItem().toString();
        if (sTypeStr != "Account Type") {
            accountType1 = sTypeStr;
        } else {
            accountType1 = "";
        }
    }//GEN-LAST:event_createSTypeActionPerformed

    private void createCTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCTypeActionPerformed

        String sTypeStr = createCType.getSelectedItem().toString();
        if (sTypeStr != "Account Type") {
            accountType2 = sTypeStr;
        } else {
            accountType2 = "";
        }
    }//GEN-LAST:event_createCTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAddPic;
    private javax.swing.JTextField createAge;
    private javax.swing.JTextField createAllergy1;
    private javax.swing.JTextField createAllergy2;
    private javax.swing.JTextField createAllergy3;
    private javax.swing.JTextField createBloodType;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField createCAccount;
    private javax.swing.JTextField createCBalance;
    private javax.swing.JTextField createCBankName;
    private javax.swing.JTextField createCRouting;
    private javax.swing.JComboBox<String> createCType;
    private javax.swing.JTextField createCity;
    private javax.swing.JTextField createCountry;
    private javax.swing.JTextField createDateOfBirth;
    private javax.swing.JTextField createDrLicNo;
    private javax.swing.JTextField createExpiryDate;
    private javax.swing.JTextField createFirstName;
    private javax.swing.JTextField createHeight;
    private javax.swing.JTextField createIssueDate;
    private javax.swing.JTextField createLastName;
    private javax.swing.JTextField createMedicalNumber;
    private javax.swing.JTextField createPhoneNumber;
    private javax.swing.JTextField createSAccount;
    private javax.swing.JTextField createSBalance;
    private javax.swing.JTextField createSBankName;
    private javax.swing.JTextField createSRouting;
    private javax.swing.JTextField createSSN;
    private javax.swing.JComboBox<String> createSType;
    private javax.swing.JTextField createState;
    private javax.swing.JTextField createStreetLine1;
    private javax.swing.JTextField createStreetLine2;
    private javax.swing.JTextField createWeight;
    private javax.swing.JTextField createZipCode;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
