/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.DeliveryMan.DeliveryMan;
import Business.Restaurant.Restaurant;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;

/**
 *
 * @author Lingfeng
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    UserAccount userAccount;

    public MainJFrame(UserAccount userAccount) {
        this.setUndecorated(true);
        initComponents();
        system = dB4OUtil.retrieveSystem();
        changePanel(userAccount);
    }

    private void changePanel(UserAccount userAccount) {
        if (userAccount != null) {
            String greetings = "Hi";
            if (userAccount instanceof Customer){
                    greetings =  greetings + " " + ((Customer)userAccount).getName();
            }else if(userAccount instanceof Restaurant){
                    greetings =  greetings + " " + ((Restaurant)userAccount).getName();
            }else if(userAccount instanceof DeliveryMan){
                    greetings =  greetings + " " + ((DeliveryMan)userAccount).getName();
            }
            greetingUserLabel.setText(greetings + " !!!");
            CardLayout layout = (CardLayout) container.getLayout();
            container.add("workArea", userAccount.getRole().createWorkArea(container, userAccount, system));
            layout.next(container);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        greetingUserLabel = new javax.swing.JLabel();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 802));
        setPreferredSize(new java.awt.Dimension(1200, 702));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(212, 205, 179));
        leftPanel.setPreferredSize(new java.awt.Dimension(1200, 60));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        leftPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 2, 60, 60));

        greetingUserLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        leftPanel.add(greetingUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 500, 60));

        getContentPane().add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        container.setBackground(new java.awt.Color(31, 50, 97));
        container.setForeground(new java.awt.Color(31, 50, 97));
        container.setLayout(new java.awt.CardLayout());
        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 61, 1200, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        logout();
    }//GEN-LAST:event_jLabel1MousePressed

    private void logout() {
        container.removeAll();
        dB4OUtil.storeSystem(system);
        AuthenticationJFrame tf2 = new AuthenticationJFrame();
        tf2.setVisible(true);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel greetingUserLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel leftPanel;
    // End of variables declaration//GEN-END:variables

}
